mlsql:
  website:
    database:
      useSSL: false
      ip: localhost
      port: 3306
      name: mlsql_website
      username: root
      password: root

spring:
  application:
    name: Mlsql Website
  jackson:
    serialization:
      indent_output: true
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
  datasource:
    druid:
      url: jdbc:mysql://${mlsql.website.database.ip}:${mlsql.website.database.port}/${mlsql.website.database.name}?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=${mlsql.website.database.useSSL}&useTimezone=true&serverTimezone=UTC
      username: ${mlsql.website.database.username}
      password: ${mlsql.website.database.password}
      initial-size: 2
      max-active: 20
      min-idle: 5
      max-wait: 60000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: select 'x'
      validationQueryTimeout: 2
      time-between-eviction-runs-millis: 60000
      filter:
        slf4j:
          enabled: false
        wall:
          enabled: true
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      min-evictable-idle-time-millis: 300000
      connection-init-sqls: 'set names utf8;'
      keep-alive: false
      time-between-log-stats-millis: -1
      remove-abandoned: true
    schema:
      - classpath:mlsql_website.sql
    initialization-mode: always
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.office365.com
    username: common-user@kyligence.io
    password: Kylin22016
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.timeout: 25000
    properties.mail.smtp.starttls.enable: true
    properties.mail.info: true
    fromMail: mlsql_lab@kyligence.io
    default-encoding: utf-8

server:
  port: ${mlsql.website.port:3000}
  address: 0.0.0.0
  tomcat:
    accept-count: 500
    uri-encoding: UTF-8
    max-connections: 10000
    max-http-post-size: 10485760
    max-threads: 200
    min-spare-threads: 10
    max-http-header-size: 8192
    accesslog:
      enabled: true
      directory: ${WEBSITE_HOME}/logs
      pattern: '%h %l %u %t "%r" %s %b %D'
      prefix: website_access
    basedir: ${WEBSITE_HOME}
  connection-timeout: -1
  servlet:
    session:
      timeout: ${mlsql.website.session.timeout:12h}
  error:
    include-stacktrace: always

management:
  endpoint:
    shutdown:
      enabled: false


